# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac45b68fad2c2a395bc9b57cb191df60"
name = "65"
handle = "65-1"
application_url = "https://mouse-tear-curve-peripheral.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, read_checkouts, read_customers"

[auth]
redirect_urls = [
  "https://mouse-tear-curve-peripheral.trycloudflare.com/auth/callback",
  "https://mouse-tear-curve-peripheral.trycloudflare.com/auth/shopify/callback",
  "https://mouse-tear-curve-peripheral.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
