# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08bef66432be6db760de3a6b85baf419"
name = "Custom_warmlight_2"
handle = "08bef66432be6db760de3a6b85baf419"
application_url = "https://warmlight.xyz"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"
  
  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"
  

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, read_checkouts, read_customers"

[auth]
redirect_urls = [
  "https://warmlight.xyz/auth/callback",
  "https://warmlight.xyz/auth/shopify/callback",
  "https://warmlight.xyz/api/auth/callback"
]

[pos]
embedded = false
