client_id       = "ac45b68fad2c2a395bc9b57cb191df60"
name            = "65"
handle          = "65-1"
application_url = "https://warmlight.xyz"
embedded        = true

[build]
include_config_on_deploy    = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

# 1) compliance-webhooks
[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/webhooks/compliance"

# 2) יתר ה-topics
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri    = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri    = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri    = "/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = ["orders/fulfilled"]
uri    = "/webhooks/orders/fulfilled"

[[webhooks.subscriptions]]
topics = ["carts/create"]
uri    = "/webhooks/carts/create"

[[webhooks.subscriptions]]
topics = ["checkouts/create"]
uri    = "/webhooks/checkouts/create"

[access_scopes]
scopes = "write_products, read_orders, read_checkouts, read_customers"

[auth]
redirect_urls = [
  "https://warmlight.xyz/auth/callback",
  "https://warmlight.xyz/auth/shopify/callback",
  "https://warmlight.xyz/api/auth/callback"
]

[pos]
embedded = false
