# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac45b68fad2c2a395bc9b57cb191df60"
name = "65"
handle = "65-1"
application_url = "https://arise-aw-science-sparc.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arise-aw-science-sparc.trycloudflare.com/auth/callback",
  "https://arise-aw-science-sparc.trycloudflare.com/auth/shopify/callback",
  "https://arise-aw-science-sparc.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
